# ===== Server =====
//server.port=8080

# ===== Application =====
spring.application.name=student-management-system

# ===== MySQL Datasource =====
spring.datasource.url=jdbc:mysql://sms-project-abhay-db-sms-project-abhay.b.aivencloud.com:12467/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_mpXcLHk0ZPPp2tWlDm6
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===== JPA / Hibernate =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

# ===== Thymeleaf =====
spring.thymeleaf.cache=false

# ===== Logging =====
logging.level.org.springframework=INFO
logging.level.com.abhay.studentmanagementsystem=DEBUG
